### ISSUE TITLE
Docker image for English doesn't work

### ISSUE THREAD

**Issue by mkraeva-astea** [dbpedia-spotlight/spotlight-docker#11]
Trying to run the docker image for English results in
```
Exception in thread "main" java.io.IOException: Invalid Spotlight model folder: Could not read required file tokens.mem in /opt/spotlight/en/model/tokens.mem.
	at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:48)
	at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:46)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:45)
	at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:80)
	at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
	at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:229)
	at org.dbpedia.spotlight.web.rest.Server.main(Server.java:87)
```

The error seems to be caused by the name of the downloaded model - the Dockerfile refers to `en_2+2.tar.gz` instead of `en.tar.gz`.

**Comment by sandroacoelho** [comment]
OMG. Thank you @mkraeva-astea 

I have fixed it. Please wait an hour to Docker Hub recompile it.


Best,

**Comment by mkraeva-astea** [comment]
Thanks! The v1.0 image now works.
However, there is now a typo in `spotlight.sh` used for v0.7.1 and v0.7 (`/opt/spotlight//opt/spotlight/en_2+2` instead of `/opt/spotlight/en_2+2`). It would be great if you fixed them as well, in case anyone still uses those images.

**Comment by sandroacoelho** [comment]
Fixed. Thank you :)

**Comment by IratxePinedoehu** [comment]
Hi,

I'm facing this same problem right now:

Exception in thread "main" java.io.IOException: Invalid Spotlight model folder: Could not read required file tokens.mem in /opt/spotlight/models/en/model/tokens.mem.
	at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:48)
	at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:46)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:45)
	at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:80)
	at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
	at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:239)
	at org.dbpedia.spotlight.web.rest.Server.main(Server.java:87)

Thanks

**Comment by zxd-octopus** [comment]
> Hi,
> 
> I'm facing this same problem right now:
> 
> Exception in thread "main" java.io.IOException: Invalid Spotlight model folder: Could not read required file tokens.mem in /opt/spotlight/models/en/model/tokens.mem. at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:48) at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:46) at scala.collection.immutable.List.foreach(List.scala:318) at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:45) at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:80) at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala) at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:239) at org.dbpedia.spotlight.web.rest.Server.main(Server.java:87)
> 
> Thanks

It happened to me too, did you solve the problem?

**Comment by zxd-octopus** [comment]
> Hi,
> 
> I'm facing this same problem right now:
> 
> Exception in thread "main" java.io.IOException: Invalid Spotlight model folder: Could not read required file tokens.mem in /opt/spotlight/models/en/model/tokens.mem. at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:48) at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:46) at scala.collection.immutable.List.foreach(List.scala:318) at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:45) at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:80) at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala) at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:239) at org.dbpedia.spotlight.web.rest.Server.main(Server.java:87)
> 
> Thanks

I solved the problem, just manually download the missing files locally and copy them to the destination folder

**Comment by lukasbirki** [comment]
Hi [zxd-octopus](https://github.com/zxd-octopus), what do you mean you downloaded them locally? I got the exact same error as you and did try to put the .mem file in the current working directory. But it is still not working! Did you extracted all data of the tar.gz file?

**Comment by zxd-octopus** [comment]
yeah, i extracted all data of the tar.gz file and upload them to opt/spotlight/models in the container. @lukasbirki

**Comment by zxd-octopus** [comment]
yeah, i extracted all data of the tar.gz file and upload them to opt/spotlight/models in the container.

发件人：Lukas Birkenmaier ***@***.***>
发送日期：2023-10-24 03:15:36
收件人：dbpedia-spotlight/spotlight-docker ***@***.***>
抄送人：Xiaoyu Zhang ***@***.***>,Comment ***@***.***>
主题：Re: [dbpedia-spotlight/spotlight-docker] Docker image for English doesn't work (#11)

Hi zxd-octopus, what do you mean you downloaded them locally? I got the exact same error as you and did try to put the .mem file in the current working directory. But it is still not working! Did you extracted all data of the tar.gz file?
